name: Build bionic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.3.1  
        
      - name: Install repo
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/null
          sudo chmod +x /usr/bin/repo
      - name: Get source
        run: |
          repo init -u git://github.com/gamecss/bionic-minimal-manifest.git -b main --depth=1
          repo sync -c -j32 --no-tags --no-clone-bundle --optimized-fetch --prune

      - name: Build
        run: |
          source build/envysetup.sh
          lunch aosp_x86_64-eng
          cd bionic
          mm
