name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install repo
        run: |
          sudo apt-get install repo
      
      - name: Get source
        run: |
          repo init -u git://github.com/gamecss/bionic-minimal-manifest.git -b main --depth=1
          repo sync -c -j8 --no-tags --no-clone-bundle --optimized-fetch --prune

      - name: Build
        run: |
          source build/envsetup.sh
          lunch aosp_x86_64-eng
          cd bionic
          mm
